### PR TITLE
Fix/Edit job

### PR DESCRIPTION
**Pull request by kristiingco**
Description: Fix the edit logic after the integration of Redux

Type of Change (eg. fix, feature, etc):  Fix

Reason for Change: Edit logic removed after redux introduction. This fix intends to make the edit logic compatible with Redux

### CODE REVIEW

**Comment by JeremiahDMoore** [comment]
After logging in with the test123@gmail.com account, I see there are no tags on the cards like there were before. Was this what we wanted?

**Comment by kristiingco** [comment]
> After logging in with the [test123@gmail.com](mailto:test123@gmail.com) account, I see there are no tags on the cards like there were before. Was this what we wanted?
> 
> 

thanks for checking jeremiah! and strange… this isn’t happening on my end when it comes to this branch… im not sure why this is happening

**Comment by JeremiahDMoore** [comment]
oh! I may have made a mistake merging.. I will try to fix it! might need your help since your code seems to work properly... if so I will ping you on discord :)

**Comment by JeremiahDMoore** [comment]
everything looks good !

**Pull request merged**
